cd ~/workspace/osm1/js-storeman-agent
git stash
git pull
cd ~/workspace/osm2/js-storeman-agent
git stash
git pull
cd ~/workspace/osm3/js-storeman-agent
git stash
git pull
cd ~/workspace/osm4/js-storeman-agent
git stash
git pull
cd ~/workspace/osm5/js-storeman-agent
git stash
git pull
cd ~/workspace/osm6/js-storeman-agent
git stash
git pull
